name: Application CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r App/requirements.txt
        pip install pytest

    - name: Run Unit Tests
      run: pytest tests/test_app.py

    - name: Run Integration Tests
      run: pytest tests/test_integration.py

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest App

    - name: Trivy Security Scan
      uses: aquasecurity/trivy-action@v0.9.1
      with:
        image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest

    - name: Bump Version
      id: version
      run: |
        VERSION=$(cat App/VERSION)
        NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
        echo $NEW_VERSION > App/VERSION
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit Version Bump
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add App/VERSION
        git commit -m "Bump version to ${{ env.new_version }}"
        git push